apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000